---
# tasks file for configuring system
- name: set timezone to localzone
  file:
    src: "{{ localzone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: set SElinux mode
  selinux:
    policy: targeted
    state: "{{ selinux_mode }}"

- name: Change firewalld.conf for warning on AllowZoneDrifting
  replace:
    path: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting=yes'
    replace: 'AllowZoneDrifting=no'

- name: Enable and start firewalld
  service:
    name: firewalld
    enabled: true
    state: started
